# Generated by Django 4.0.3 on 2022-03-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'habit'), name='once_a_day'),
        ),
    ]
