# Generated by Django 4.0.3 on 2022-03-23 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habitapp', '0004_habit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
