# Generated by Django 4.0.3 on 2022-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitapp', '0008_alter_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
